name: RezxisMCHosting
main: net.rezxis.mchosting.spigot.RezxisMCHosting
version: 0.2
depend: [RezxisSQLPlugin]
commands:
  realm:
    description: open server manager
  realmtest:
    description: open server manager
  sa:
    description: open server manager